#!/usr/bin/env python3
import sys

FILE = "/workspace/0a976afa-9d91-494d-85d2-5832b5541cb3/sessions/agent_da75a3e4-21f8-4acf-b54c-2ef479e28b4e/RH-Resisting-Resistance-To-Find-Happiness/BOOK.md"

replacements = [
    ("the internal force that keeps us from doing what we know is good", "the internal force of laziness, fear, doubt, and procrastination that keeps us from doing what we know is good"),
    ("good", "what is good for us and others"),
    ("the happiness God intends for us", "the deep, lasting joy God intends for us"),
    ("slay the dragon of resistance", "overcome resistance"),
    ("the person God created you to be", "the person God calls you to become"),
    ("the opinions of critics", "the negative opinions of critics"),
    ("Resistance wears a thousand masks", "Resistance appears in many forms"),
    ("laziness, procrastination, fear, doubt, instant gratification, self-loathing, indecision, escapism, pride, self-deception, friction, tension, and self-sabotage", "laziness, procrastination, fear, doubt, instant gratification, self-loathing, indecision, escapism, pride, self-deception, friction, tension, self-sabotage, and other subtle forms"),
    ("Isolation feeds resistance", "Isolation reinforces resistance by removing accountability"),
    ("the concept of resistance", "resistance itself"),
    ("inaction", "failing to take positive action"),
    ("track patterns", "track behavioral patterns in a journal"),
    ("recurring forms of resistance", "forms of resistance that appear repeatedly"),
    ("trusted friend or spiritual coach", "trusted friend or trained spiritual coach"),
    ("small victories", "small, specific victories"),
    ("a thousand masks", "many forms"),
    ("The hardest war to win", "A difficult battle to win"),
    ("resistance to vulnerability", "resistance to being vulnerable"),
    ("seeking help", "seeking help from a trusted person or professional"),
    ("the concept of resistance", "resistance"),
    ("inaction", "failing to take action"),
    ("defeated resistance permanently", "permanently eliminated resistance from your life"),
    ("fight it again", "choose to act against it again"),
    ("falling to resistance", "succumbing to resistance"),
    ("start anew", "start anew with one small positive choice"),
    ("turn it all around", "turn your situation around with one intentional action"),
    ("God-size hole", "a deep longing for God"),
    ("gnawing dissatisfaction", "a persistent sense of dissatisfaction that lasts for weeks"),
    ("things, money, status, power, sex, drugs, alcohol, other people, experiences, or accomplishments", "material possessions, money, status, power, relationships, experiences, or achievements"),
    ("when you place anything else at the center of your life", "when you place anything other than God at the center of your life"),
    ("the desire for God", "the longing for God"),
    ("written on your heart", "a deep inner sense"),
    ("draw you to him", "draw you toward him through prayer, community, and Scripture"),
    ("the truth and happiness you are looking for", "the truth and joy you are seeking"),
    ("the whole meaning and purpose of your existence", "the meaning and purpose God intends for your life"),
    ("lose their meaning", "feel empty or without direction"),
    ("resistance to prayer", "resistance to praying"),
    ("if it can keep you from praying", "if it can keep you from praying regularly"),
    ("many more battles", "additional challenges"),
    ("throughout the day", "in the hours and decisions that follow"),
    ("He already knows your heart", "He already knows your thoughts and feelings"),
    ("Treating prayer as one more task to check off the list", "Treating prayer as one more item on a to-do list"),
    ("a relationship, not a ritual", "a genuine conversation, not a routine recitation"),
    ("relationship", "genuine connection"),
    ("ritual", "routine recitation"),
    ("over time", "over days, weeks, or months"),
    ("quiet whispers", "gentle promptings"),
    ("Only the insane and egomaniacal", "This stubborn resistance can appear in anyone"),
    ("God is happiness", "God is the source of true joy"),
    ("his dream for you", "the good life God calls you to"),
    ("free will", "the freedom to choose"),
    ("others' free will", "the free will of the person you care about"),
    ("something they are not ready for", "a change or choice they are not yet open to"),
    ("the discipline required for true happiness", "the consistent choices required for lasting joy"),
    ("true happiness", "deep, lasting joy"),
    ("slay it like a dragon", "consciously choose to act against it"),
    ("anew each day", "anew each morning"),
    ("realism", "practical clarity"),
    ("we resist happiness", "we resist choosing the joy God offers"),
    ("all sorts of things", "many forms of resistance"),
    ("all sorts of reasons", "many reasons"),
    ("it usually comes down to this", "this pattern often appears"),
    ("insatiable desire for happiness", "a deep, persistent longing for meaning and joy"),
    ("Nobody gets to escape", "No one is exempt from facing"),
    ("popes and presidents, kings and janitors, rich and poor, educated and uneducated, young and old", "people in all roles, statuses, and stages of life"),
    ("when you resist what you know is good", "when you resist what you recognize as good"),
    ("The author, an accomplished writer with twenty books, battles resistance daily", "Even experienced writers battle resistance daily"),
    ("it affects you", "it likely appears in your life too"),
    ("You never defeat resistance once and for all", "You may break through a specific instance of resistance, but the force itself returns"),
    ("fight again tomorrow", "choose to act against it again tomorrow"),
    ("Resistance is not creativity", "Resistance is not the spark of inspiration"),
    ("Resistance is the enemy of creativity", "Resistance is the force that kills the spark before it can catch"),
    ("The path of least resistance", "Choosing the easiest option"),
    ("effortlessly creates", "often creates"),
    ("negative routines, rituals, and rhythms", "negative routines and habits"),
    ("spend your way to happiness", "spend money hoping it will bring contentment"),
    ("deal with emotions", "manage difficult emotions"),
    ("resistance loves", "resistance reinforces"),
    ("prayer", "a few minutes of prayer"),
    ("bulletproof recipe", "highly effective combination"),
    ("exponentially", "significantly"),
    ("fabulous day", "meaningful day"),
    ("they", "Strong positive habits"),
    ("three best habits", "three helpful habits"),
    ("best", "helpful"),
    ("need to change", "want to change"),
    ("brutally honest", "completely honest"),
    ("great new habit", "positive new habit"),
    ("today", "within the next 24 hours"),
    ("Strong habits", "Good habits"),
    ("Good habits", "Good habits"),
    ("effortlessly", "easily"),
    ("Resistance hates", "Resistance opposes"),
    ("God loves ordinary things", "God can be found in ordinary activities"),
    ("Every hour of work", "Every hour of productive work"),
    ("ordinary activity", "ordinary daily activity"),
    ("every ordinary activity", "any appropriate ordinary activity"),
    ("can be transformed", "can be offered to God"),
    ("into prayer", "as an act of prayer"),
    ("ten seconds per hour", "at least ten seconds per hour"),
    ("one bad habit", "one habit at a time"),
    ("another", "another habit"),
    ("everything", "all your habits"),
    ("one habit at a time", "ideally one habit at a time"),
    ("Small", "Small, incremental"),
    ("dramatic overhauls", "complete life overhauls"),
    ("a day", "one day"),
    ("entirely", "completely"),
    ("failure", "a setback"),
    ("the next day", "the following calendar day"),
    ("on track", "moving in a positive direction"),
    ("Motivation", "The feeling of motivation"),
    ("Motivation follows action", "The feeling of motivation often comes after taking action"),
    ("do not feel like it", "do not feel motivated"),
    ("not the other way around", "though there are exceptions"),
    ("We have so much to be happy about", "We have relationships, health, and opportunities that bring meaning"),
    ("it is easy to lose sight of this", "losing sight of this abundance is easy"),
    ("an overwhelming amount of suffering", "a significant amount of suffering visible in the world"),
    ("amount of suffering", "suffering such as illness, loss, or injustice"),
    ("what you have", "your relationships, health, and shelter"),
    ("what you lack", "your perceived shortcomings or unmet desires"),
    ("the present moment", "the current hour"),
    ("Gratitude rewires your brain", "Practicing gratitude strengthens positive thinking patterns"),
    ("the good", "positive aspects of your life"),
    ("already present", "already present in your daily life"),
    ("remember this", "remember that every moment offers a new chance"),
    ("every moment", "each new moment"),
    ("a new chance", "a new chance to choose a positive response"),
    ("turn it all around", "turn your situation around by identifying one small change"),
    ("the final word", "the final say over your life's direction"),
    ("You do", "You choose the outcome"),
    ("When you do break through resistance", "If and when you break through resistance"),
    ("celebrate that", "celebrate breaking through"),
    ("press on", "press on by setting one new goal"),
    ("Do not just survive resistance; thrive in spite of it", "Do not just endure resistance; grow through it"),
    ("thrive", "grow in patience and generosity"),
    ("with ten items each day", "with ten items, a number chosen to encourage depth without overwhelm"),
    ("blessings", "specific things you appreciate"),
    ("When discouraged", "When you feel unmotivated or disheartened"),
    ("past victories", "past successes such as completing a difficult task"),
    ("the battle", "the ongoing effort to overcome resistance"),
    ("what matters most and what matters least", "what matters most is your relationship with God and others, and what matters least is material possessions"),
    ("once you get into the habit of beating it", "if you develop the habit of overcoming it"),
    ("that knowledge", "this knowledge"),
    ("becomes very powerful", "becomes a reliable tool for overcoming daily challenges"),
    ("All great stories", "Many great stories"),
    ("villain and a hero", "villain and hero as narrative roles representing internal struggle"),
    ("complacency", "satisfaction without continued growth"),
    ("keep growing", "continue learning and improving"),
    ("things go well", "your plans succeed and you feel content"),
    ("things are difficult", "you face setbacks or disappointment"),
    ("one bad moment", "one moment of failure or disappointment"),
    ("your perspective", "your outlook on life"),
    ("one bad moment does not define your life", "one moment of failure does not define your life"),
    ("your gratitude list", "the gratitude list you keep in your journal"),
    ("nothing to be grateful for", "few things you are aware of being grateful for"),
    ("the basics", "basic gifts such as health, shelter, and food"),
    ("Build from there", "Build from there by adding one relationship or experience you appreciate each day"),
    ("each chapter", "each chapter of the book"),
    ("the lesson", "the main lesson"),
    ("living out your full potential and purpose", "living out your full potential by using your gifts in service to others"),
    ("every single day", "on most days"),
    ("The innate human longing for God", "For many people, the innate human longing for God"),
    ("anything earthly", "anything material or temporary"),
    ("the present moment", "the current day or hour"),
    ("God's nature", "God's character as loving, just, and truthful"),
    ("Objective reality", "facts that are true regardless of personal belief"),
    ("a consumer mindset", "a mindset that approaches life as a series of transactions to maximize personal pleasure"),
    ("expecting everything to go as planned", "expecting life to always go according to personal plans"),
    ("overcome resistance", "overcome resistance by consistently choosing positive actions despite fear or doubt"),
    ("shapes our destiny", "shapes our daily choices and long-term outcomes"),
    ("either defeating or feeding resistance", "defeating resistance by taking positive action, or feeding it by procrastinating"),
    ("A central truth", "A central truth, or the most important takeaway"),
    ("Everyday activities and moments", "Everyday activities such as eating, working, and commuting"),
    ("through which God can be encountered and experienced", "through which God can be encountered in moments of peace or insight"),
    ("a spiritual journey", "a spiritual journey marked by prayer, service, and growing faith"),
    ("who sees life as temporary", "who sees earthly life as temporary"),
    ("heaven as the true home", "who believe heaven is their true home"),
    ("A structured prayer method", "A structured prayer method with six steps"),
    ("significant moments", "significant moments, or events that stand out as meaningful or challenging"),
    ("and others", "and intercession for others"),
    ("The internal force", "The internal force of laziness, fear, doubt, and procrastination"),
    ("stands between us and happiness", "stands between us and a sense of purpose and contentment"),
    ("spiritual life", "spiritual life, or your relationship with God and practice of faith"),
    ("overcome resistance", "overcome resistance by consistently choosing positive actions despite fear or doubt"),
    ("Resistance", "The internal force of laziness, fear, doubt, and procrastination that stands between us and happiness"),
]

with open(FILE, 'r') as f:
    content = f.read()

for i, (search, replace) in enumerate(replacements, 1):
    if search in content:
        print(f"EXISTS ({i}): '{search}'")
    else:
        print(f"MISSING ({i}): '{search}'")

